---
- name: Download Kafka 2.1.0 binaries
  get_url:
    url: https://archive.apache.org/dist/kafka/2.1.0/kafka_2.11-2.1.0.tgz
    dest: /tmp

- name: Unpack Kafka binaries
  unarchive:
    src: /tmp/kafka_2.11-2.1.0.tgz
    dest: /usr
    remote_src: yes

- name: Start Zookeeper
  shell:
    cmd: bin/zookeeper-server-start.sh config/zookeeper.properties > /dev/null 2>&1 &
    chdir: /usr/kafka_2.11-2.1.0

- name: Start a Kafka broker
  shell:
    cmd: bin/kafka-server-start.sh config/server.properties > /dev/null 2>&1 &
    chdir: /usr/kafka_2.11-2.1.0
